export const FETCH_CEPUB_START = 'FETCH_CEPUB_START';
export const FETCH_CEPUB_SUCCESS = 'FETCH_CEPUB_SUCCESS';
export const FETCH_CEPUB_FAIL = 'FETCH_CEPUB_FAIL';

export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const FETCH_NEWSDETAIL_START = 'FETCH_NEWSDETAIL_START';
export const FETCH_NEWSDETAIL_SUCCESS = 'FETCH_NEWSDETAIL_SUCCESS';
export const FETCH_NEWSDETAIL_FAIL = 'FETCH_NEWSDETAIL_FAIL';

export const FETCH_CIPAR_START = 'FETCH_CIPAR_START';
export const FETCH_CIPAR_SUCCESS = 'FETCH_CIPAR_SUCCESS';
export const FETCH_CIPAR_FAIL = 'FETCH_CIPAR_FAIL';

export const FETCH_YOUTH_START = 'FETCH_YOUTH_START';
export const FETCH_YOUTH_SUCCESS = 'FETCH_YOUTH_SUCCESS';
export const FETCH_YOUTH_FAIL = 'FETCH_YOUTH_FAIL';


export const FETCH_ECOLOGI_START = 'FETCH_ECOLOGI_START';
export const FETCH_ECOLOGI_SUCCESS = 'FETCH_ECOLOGI_SUCCESS';
export const FETCH_ECOLOGI_FAIL = 'FETCH_ECOLOGI_FAIL';

export const FETCH_PUBDETAIL_START = 'FETCH_PUBDETAIL_START';
export const FETCH_PUBDETAIL_SUCCESS = 'FETCH_PUBDETAIL_SUCCESS';
export const FETCH_PUBDETAIL_FAIL = 'FETCH_PUBDETAIL_FAIL';

export const FETCH_SUCCESS_STORIES_START = 'FETCH_SUCCESS_STORIES_START';
export const FETCH_SUCCESS_STORIES_SUCCESS = 'FETCH_SUCCESS_STORIES_SUCCESS';
export const FETCH_SUCCESS_STORIES_FAIL = 'FETCH_SUCCESS_STORIES_FAIL';

export const FETCH_REPORTS_PDFDATA_START = 'FETCH_REPORTS_PDFDATA_START';
export const FETCH_REPORTS_PDFDATA_SUCCESS = 'FETCH_REPORTS_PDFDATA_SUCCESS';
export const FETCH_REPORTS_PDFDATA_FAIL= 'FETCH_REPORTS_PDFDATA_FAIL';

export const FETCH_FEEDBACK_FROMBENEF_START= 'FETCH_FEEDBACK_FROMBENEF_START';
export const FETCH_FEEDBACK_FROMBENEF_SUCCESS= 'FETCH_FEEDBACK_FROMBENEF_SUCCESS';
export const FETCH_FEEDBACK_FROMBENEF_FAIL= 'FETCH_FEEDBACK_FROMBENEF_FAIL';

export const FETCH_DONORS_EVALUATION_START = 'FETCH_DONORS_EVALUATION_START ';
export const FETCH_DONORS_EVALUATION_SUCCESS = 'FETCH_DONORS_EVALUATION_SUCCESS ';
export const FETCH_DONORS_EVALUATION_FAIL = 'FETCH_DONORS_EVALUATION_FAIL ';

export const FETCH_STORIESDETAIL_START = 'FETCH_STORIESDETAIL_START ';
export const FETCH_STORIESDETAIL_SUCCESS = 'FETCH_STORIESDETAIL_SUCCESS ';
export const FETCH_STORIESDETAIL_FAIL = 'FETCH_STORIESDETAIL_FAIL ';

export const FETCH_PUBLICATIONDETAIL_START = 'FETCH_PUBLICATIONDETAIL_START ';
export const FETCH_PUBLICATIONDETAIL_SUCCESS = 'FETCH_PUBLICATIONDETAIL_SUCCESS ';
export const FETCH_PUBLICATIONDETAIL_FAIL = 'FETCH_PUBLICATIONDETAIL_FAIL ';

export const FETCH_LANGUAGE_START = 'FETCH_LANGUAGE_START ';
export const FETCH_LANGUAGE_SUCCESS = 'FETCH_LANGUAGE_SUCCESS ';
export const FETCH_LANGUAGE_FAIL = 'FETCH_LANGUAGE_FAIL ';

export const FETCH_PARTNERS_START = 'FETCH_PARTNERS_START ';
export const FETCH_PARTNERS_SUCCESS = 'FETCH_PARTNERS_SUCCESS ';
export const FETCH_PARTNERS_FAIL = 'FETCH_PARTNERS_FAIL ';

export const FETCH_OURTEAM_START = 'FETCH_OURTEAM_START ';
export const FETCH_OURTEAM_SUCCESS = 'FETCH_OURTEAM_SUCCESS ';
export const FETCH_OURTEAM_FAIL = 'FETCH_OURTEAM_FAIL ';

export const FETCH_SLIDER_START = 'FETCH_SLIDER_START ';
export const FETCH_SLIDER_SUCCESS = 'FETCH_SLIDER_SUCCESS ';
export const FETCH_SLIDER_FAIL = 'FETCH_SLIDER_FAIL ';

export const FETCH_BOARD_MEMBER_START = 'FETCH_BOARD_MEMBER_START ';
export const FETCH_BOARD_MEMBER_SUCCESS = 'FETCH_BOARD_MEMBER_SUCCESS ';
export const FETCH_BOARD_MEMBER_FAIL = 'FETCH_BOARD_MEMBER_FAIL ';

export const FETCH_YOUTHDEVELOPMENTDETAIL_START = 'FETCH_YOUTHDEVELOPMENTDETAIL_START';
export const FETCH_YOUTHDEVELOPMENTDETAIL_SUCCESS = 'FETCH_YOUTHDEVELOPMENTDETAIL_SUCCESS';
export const FETCH_YOUTHDEVELOPMENTDETAIL_FAIL = 'FETCH_YOUTHDEVELOPMENTDETAIL_FAIL';

export const FETCH_ECOLOGIDETAIL_START = 'FETCH_ECOLOGIDETAIL_START ';
export const FETCH_ECOLOGIDETAIL_SUCCESS = 'FETCH_ECOLOGIDETAIL_SUCCESS ';
export const FETCH_ECOLOGIDETAIL_FAIL = 'FETCH_ECOLOGIDETAIL_FAIL ';

export const FETCH_PARTICIPATION_START = 'FETCH_PARTICIPATION_START ';
export const FETCH_PARTICIPATION_SUCCESS = 'FETCH_PARTICIPATION_SUCCESS ';
export const FETCH_PARTICIPATION_FAIL = 'FETCH_PARTICIPATION_FAIL ';
